### ISSUE TITLE
Run flow and prettier eslint on Travis

### ISSUE THREAD

**Issue by rgbkrk** [nteract/commuter#150]
It would be great to see flow and prettier get checked on travis.

Note: only the commuter-server has flow setup.

**Comment by cabhishek** [comment]
Maybe a pre-commit hook using [lint-staged](https://github.com/okonet/lint-staged) can helpful?

**Comment by rgbkrk** [comment]
Yeah, we use that on nteract/nteract, I think bringing it over here would be good too.
