### ISSUE TITLE
commuter  screen shots

### ISSUE THREAD

**Issue by cabhishek** [nteract/commuter#19]
![screen shot 2017-02-13 at 11 19 45 am](https://cloud.githubusercontent.com/assets/146449/22899082/6efa3ddc-f1de-11e6-98f7-596bdda382ad.png)

**Comment by cabhishek** [comment]
Need to improve and add more features like create/delete/rename notebooks

**Comment by cabhishek** [comment]
![screen shot 2017-02-13 at 11 15 57 am](https://cloud.githubusercontent.com/assets/146449/22898931/f272a740-f1dd-11e6-877f-551a1bdb01fa.png)

**Comment by rgbkrk** [comment]
Done in #39
