### ISSUE TITLE
Prepare and move commuter to nteract monorepo

### ISSUE THREAD

**Issue by willingc** [nteract/commuter#243]
This would be a good item for the upcoming sprints.

**Comment by rgbkrk** [comment]
😄  I'm in progress with it in https://github.com/nteract/nteract/pull/2155 😄

**Comment by riordan** [comment]
Is this an issue that's ready to close now that it's back out of the monorepo?

(welcome back)

**Comment by rgbkrk** [comment]
Hahah, yes indeed.
