### ISSUE TITLE
Is it possible to hide input cells?

### ISSUE THREAD

**Issue by adammclaurin** [nteract/commuter#310]
Is it possible to configure Commuter to hide the input cells in the rendered output? E.g. how nbconvert would behave with HTMLExporter.exclude_input set to True.

Thanks!

**Comment by captainsafia** [comment]
@adammclaurin We don't currently support this at the moment -- but a PR is welcome!

**Comment by adammclaurin** [comment]
Thanks for the feedback @captainsafia
