### ISSUE TITLE
Can Commuter be password protected? 

### ISSUE THREAD

**Issue by adammclaurin** [nteract/commuter#311]
We have some notebooks that we're considering sharing via Commuter that require restricted access. Can Commuter be password protected?

**Comment by captainsafia** [comment]
Commuter itself cannot be password protected. However, you can host the notebooks on AWS/Google and use the permissions features there to limit accessibility. Does that work for you?

**Comment by adammclaurin** [comment]
Thanks for the feedback @captainsafia. I think in our case we'll have to create a custom implementation and use Commuter as inspiration.
