### ISSUE TITLE
[bug] Author field not getting populated on the Discover UI 

### ISSUE THREAD

**Issue by cabhishek** [nteract/commuter#77]
![screen shot 2017-03-07 at 11 32 15 am](https://cloud.githubusercontent.com/assets/146449/23674153/c4ad19dc-0329-11e7-9d01-0ae6f668d452.png)

**Comment by rgbkrk** [comment]
It looks like the discovery API is not returning metadata in the nbformat schema, authors needs to be an array of Objects like `[{ name: "Kyle Kelley" }, { name: "Abhishek Kapatkar" }]`

https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbformat.v4.schema.json#L73

**Comment by rgbkrk** [comment]
On the UI side, we could do some better API validation and recovery. Especially since this is a case of the elasticsearch data not matching spec.
