### ISSUE TITLE
Support auth via aws_access_key_id & aws_secret_access_key 

### ISSUE THREAD

**Issue by cabhishek** [nteract/commuter#8]
Implementation details [here](https://aws.amazon.com/sdk-for-node-js/)

Right now only `IAM_ROLE` auth works.

**Comment by rgbkrk** [comment]
The Amazon environment variables work automatically too right? AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, Etc.?

**Comment by cabhishek** [comment]
not sure about environment variables but a credentials file at `~/.aws/credentials` on Mac/Linux should work automatically 

```
[default]
aws_access_key_id = your_access_key
aws_secret_access_key = your_secret_key
```

**Comment by cabhishek** [comment]
@rgbkrk commuter supports `COMMUTER_S3_KEY` and `COMMUTER_S3_SECRET` env variables
