### ISSUE TITLE
npm run start script doesn't restart failed processes

### ISSUE THREAD

**Issue by rgbkrk** [nteract/commuter#80]
If the server dies, the client stays running and you have to restart the entire thing.

**Comment by cabhishek** [comment]
You could run `npm run client` and `npm run server:watch` in separate tab for auto restart.

**Comment by rgbkrk** [comment]
The main thing I'm running into right now is figuring out [how `create-react-app` chooses whether to proxy or not](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#proxying-api-requests-in-development). I'm beginning to think about using the webpack dev middleware instead of the create react app proxy.

**Comment by rgbkrk** [comment]
Ah this is it:

> Any unrecognized request without a text/html accept header will be redirected to the specified proxy.

That's how/why API requests (done over fetch) work well and why I couldn't get relative images to load. Ok, I'll get this worked out.
